# Generated by Django 4.2.11 on 2025-11-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('contrasena', models.CharField(help_text='Almacenar hashed/backed value, no texto plano', max_length=128)),
                ('n_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('n_documento', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CAJA', 'Caja'), ('UNIDAD', 'Unidad')], default='CREADO', max_length=10)),
                ('f_entrada', models.DateField(auto_now_add=True)),
                ('f_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=9, unique=True)),
                ('n_empresa', models.CharField(max_length=50)),
                ('contacto', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('n_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('p_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.producto')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_productos', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor')),
            ],
            options={
                'db_table': 'proveedor_producto',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
    ]
