# Generated by Django 4.2.11 on 2025-11-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('CAJA', 'Caja'), ('BL', 'Bl'), ('UNIDAD', 'Unidad')], default='CREADO', max_length=10),
        ),
    ]
